### ISSUE TITLE
Check for Updates prompts you to install update which not portable setup?

### ISSUE THREAD

**Issue by fogoat** [portapps/wireshark-portable#1]
When I checked for updates, it seems the install update is a full setup installer

![image](https://user-images.githubusercontent.com/6989799/64802416-75f29980-d53f-11e9-9af9-be6650397c3c.png)

![image](https://user-images.githubusercontent.com/6989799/64802422-79862080-d53f-11e9-95ed-c992fc21efe6.png)

![image](https://user-images.githubusercontent.com/6989799/64802429-7e4ad480-d53f-11e9-8c57-5ba5e83439b2.png)

![image](https://user-images.githubusercontent.com/6989799/64802436-8145c500-d53f-11e9-89b1-e39b73f68334.png)

![image](https://user-images.githubusercontent.com/6989799/64802439-8571e280-d53f-11e9-94fc-3af3718ffe40.png)

![image](https://user-images.githubusercontent.com/6989799/64802444-89056980-d53f-11e9-830a-012b067c8f7f.png)

![image](https://user-images.githubusercontent.com/6989799/64802448-8c005a00-d53f-11e9-90f2-692ce6fbd15c.png)

**Comment by crazy-max** [comment]
Hi @sunk818, yes indeed I will disable this behaviour on next release.

**Comment by crazy-max** [comment]
Solved in latest release
