### ISSUE TITLE
Command failed error="exit status 3221225781"

### ISSUE THREAD

**Issue by nurbles** [portapps/wireshark-portable#22]
### Behaviour
Wireshark will not start and logs the failure **Command failed error="exit status 3221225781"**

#### Steps to reproduce this issue

1. Download wireshark-portable-win64-3.4.2-15-setup.exe from portapps.io
2. Install to a USB thumb drive where PortableApps had been previously installed
3. Try to run from the PortableApps menu, or directly by running wireshark-portable.exe

#### Expected behaviour

I expected the _portable_ app to start and open its initial window on any Windows 10 x64 computer where I tried to use it.

#### Actual behaviour

The program ran fine on my Win 10 Pro x64 development desktop (where I ran the installer) but logs the failure on the four different, fresh Windows 10 Pro x64 installs where I have tried to use it.

[EDIT]  The machine the portable Wireshark ran OK already has a non-portable install of Wireshark.  I did not expect that to affect the _portable installer_, but perhaps it caused the installer to omit one or more critical components?

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : wireshark-portable-win64-3.4.2-15-setup.exe

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 Pro 64 bits

**Winver screenshot** : 
![winver](https://user-images.githubusercontent.com/14079927/102788771-2a00e800-4371-11eb-8db3-23123c0add9c.png)

### Screenshots

n/a

### Logs

Join the log file `log\[appname]-portable.log` to this issue.
[wireshark-portable.log](https://github.com/portapps/wireshark-portable/files/5724883/wireshark-portable.log)

**Comment by crazy-max** [comment]
Dependencies are required: https://portapps.io/app/wireshark-portable/#dependencies
